# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x05proto\":\n\x07NewTodo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"C\n\x04Todo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\n\n\x02id\x18\x04 \x01(\t2:\n\x0bTodoService\x12+\n\nCreateTodo\x12\x0e.proto.NewTodo\x1a\x0b.proto.Todo\"\x00\x42\x17Z\x15\x65xample.com/grpc-todob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025example.com/grpc-todo'
  _globals['_NEWTODO']._serialized_start=21
  _globals['_NEWTODO']._serialized_end=79
  _globals['_TODO']._serialized_start=81
  _globals['_TODO']._serialized_end=148
  _globals['_TODOSERVICE']._serialized_start=150
  _globals['_TODOSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
